name: Deploy GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
        
    - name: Install DocFX
      run: dotnet tool install -g docfx
        
    - name: Build Documentation
      run: |
        # Clean up any existing generated files
        rm -rf docs/_site docs/api
        
        # Create API documentation directory
        mkdir -p docs/api
        
        # Generate API documentation
        docfx metadata docs/docfx.json
        
        # Build the documentation site
        docfx build docs/docfx.json --force
        
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: docs/_site
        branch: gh-pages
