name: Deploy GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
        
    - name: Install DocFX
      run: dotnet tool install -g docfx
        
    - name: Build Documentation
      run: |
        # Clean up any existing generated files
        rm -rf docs/_site docs/api
        
        # Create API documentation directory
        mkdir -p docs/api
        
        # Generate API documentation
        docfx metadata docs/docfx.json
        
        # Build the documentation site
        docfx build docs/docfx.json

    - name: Setup Pages
      uses: actions/configure-pages@v4
        
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs/_site
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
